version: '3.8'
services:
  twitter_postgres_db:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=t3_db
      - POSTGRES_USER=t3_dev
      - POSTGRES_PASSWORD=t3_dev
    ports:
      - 6656:5432
    volumes:
      - t3_db_data:/data/db
volumes:
  t3_db_data:
